#version: '3.8'
services:
  app:
    image: sales_support-app:with-pgsql
    container_name: sales_support_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - sales_support_network
  db:
    image: mysql:8.0
    container_name: sales_support_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sales_support
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    networks:
      - sales_support_network
  nginx:
    image: nginx:alpine
    container_name: sales_support_nginx
    restart: unless-stopped
    ports:
      - "8090:80"
    volumes:
      - .:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - sales_support_network
networks:
  sales_support_network:
    driver: bridge
volumes:
  dbdata:
